project:
  type: website

website:
  title: "STAT240 — Multivariate Analysis: Theory, Methods, and Practice"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: lectures/index.qmd
        text: Lecture Notes
      - href: assignments/index.qmd
        text: Assignments
      - href: exams/index.qmd
        text: Exams

format:
  html:
    theme: cosmo
    toc: true